[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.poetry.scripts]
app = "backend.app:app"

[tool.poetry.dependencies]
fastapi = "^0.68.0"
uvicorn = "^0.15.0"
